version: '3.7'
services:
  python-miio:
    image: aarongorka/python-miio
    build: .
    env_file: .env
    network_mode: host  # broadcast scans
    volumes:
      - .:/work:Z
    working_dir: /work

  envvars:
    image: flemay/envvars:0.0.6
    env_file: .env
    working_dir: /work
    volumes:
      - .:/work
